#!/usr/bin/env bash

name() {
  nmcli | grep "^wl" | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2-
}


symbol() {
[ $(cat /sys/class/net/w*/operstate) = down ] && echo "󰖪"  && exit
echo "󰖩"
}

state () {
  [ $(cat /sys/class/net/w*/operstate) = down ] && echo "down" && exit
  echo "up"
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
[ "$1" = "state" ] && state && exit